# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I api/proto api/proto/sso/v1/sso.proto --go_out=./pkg/gen/go --go_opt=paths=source_relative --go-grpc_out=./pkg/gen/go --go-grpc_opt=paths=source_relative